[project]
name = "blueberry"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "ipykernel>=6.29.5",
    "mkdocs-material>=9.6.3",
    "pydantic>=2.10.6",
]
